# Default config file for Jord planetary structure code

[InputParameter]
planet_mass = 5.972e24              #  kg (Earth = 5.972e24)

[AssumptionsAndInitialGuesses]
core_radius_fraction = 0.545        # Core radius fraction of total radius
core_mass_fraction = 0.32           # Core mass fraction of total mass

[EOS]
choice                  = "Tabulated"  # Options: "Birch-Murnaghan", "Mie-Gruneisen-Debye", "Tabulated"

[Calculations]
num_layers              = 100       # Number of planet layers

[IterativeProcess]
max_iterations_outer    = 100
tolerance_outer         = 1e-4
max_iterations_inner    = 100
tolerance_inner         = 1e-4

[PressureAdjustment]
target_surface_pressure = 101325    # Pa, 1 atm, for example
pressure_tolerance      = 1000      # Pa, tolerance for surface pressure matching
max_iterations_pressure = 100       # Maximum iterations for pressure adjustment
pressure_relaxation     = 0.5       # Relaxation factor for pressure adjustment
pressure_adjustment_factor = 0.95   # Reduction factor for pressure adjustment

[Output]
data_enabled            = true      # Produces output data
plots_enabled           = true      # Produces plots
